FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish UdpHosts/MatrixServer/MatrixServer.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 25000/udp
ENTRYPOINT ["dotnet", "MatrixServer.dll"]
